-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2025-09-18 14:54:23 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

USE mgpu_ico_db_04;

CREATE TABLE booking (
    booking_id            INTEGER NOT NULL,
    booking_date          DATE NOT NULL,
    check_in_date         DATE NOT NULL,
    check_out_date        DATE NOT NULL,
    guest_count           INTEGER NOT NULL,
    rooms_room_id         INTEGER NOT NULL,
    customers_customer_id INTEGER NOT NULL
);

ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( booking_id );

CREATE TABLE booking_status (
    status_id   INTEGER NOT NULL,
    status_name VARCHAR(50) NOT NULL
);

ALTER TABLE booking_status ADD CONSTRAINT booking_status_pk PRIMARY KEY ( status_id );

CREATE TABLE booking_status_history (
    history_id               INTEGER NOT NULL,
    status_date              DATE NOT NULL,
    booking_booking_id       INTEGER NOT NULL,
    booking_status_status_id INTEGER NOT NULL
);

ALTER TABLE booking_status_history ADD CONSTRAINT booking_status_history_pk PRIMARY KEY ( history_id,
                                                                                          booking_booking_id );

CREATE TABLE customers (
    customer_id   INTEGER NOT NULL,
    fio           VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    phone_number  VARCHAR(20),
    passport_data VARCHAR(20) NOT NULL
);

ALTER TABLE customers ADD CONSTRAINT customers_pk PRIMARY KEY ( customer_id );

CREATE TABLE hotels (
    hotel_id      INTEGER NOT NULL,
    h_name        VARCHAR(100) NOT NULL,
    h_city        VARCHAR(20) NOT NULL,
    h_star_rating INTEGER NOT NULL,
    h_address     VARCHAR(200)
);

ALTER TABLE hotels ADD CONSTRAINT hotels_pk PRIMARY KEY ( hotel_id );

CREATE TABLE room_type (
    room_type_id INTEGER NOT NULL,
    type_name    VARCHAR(20) NOT NULL,
    capacity     INTEGER NOT NULL
);

ALTER TABLE room_type ADD CONSTRAINT room_type_pk PRIMARY KEY ( room_type_id );

CREATE TABLE rooms (
    room_id                INTEGER NOT NULL,
    number               VARCHAR(10) NOT NULL,
    price_per_night        INTEGER NOT NULL,
    floor                  INTEGER,
    hotels_hotel_id        INTEGER NOT NULL,
    room_type_room_type_id INTEGER NOT NULL
);

ALTER TABLE rooms ADD CONSTRAINT rooms_pk PRIMARY KEY ( room_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_customers_fk FOREIGN KEY ( customers_customer_id )
        REFERENCES customers ( customer_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_rooms_fk FOREIGN KEY ( rooms_room_id )
        REFERENCES rooms ( room_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE booking_status_history
    ADD CONSTRAINT booking_status_history_booking_fk FOREIGN KEY ( booking_booking_id )
        REFERENCES booking ( booking_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE booking_status_history
    ADD CONSTRAINT booking_status_history_booking_status_fk FOREIGN KEY ( booking_status_status_id )
        REFERENCES booking_status ( status_id );

ALTER TABLE rooms
    ADD CONSTRAINT rooms_hotels_fk FOREIGN KEY ( hotels_hotel_id )
        REFERENCES hotels ( hotel_id );

ALTER TABLE rooms
    ADD CONSTRAINT rooms_room_type_fk FOREIGN KEY ( room_type_room_type_id )
        REFERENCES room_type ( room_type_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
